### ISSUE TITLE
[User] 如何修改會員所屬會員群組？

### ISSUE THREAD

**Issue by littlegreening** [DaydreamLab/user#2]

**Comment by ppuff1988** [comment]
請見 POST /admin/user/store
有多一個鍵值group_ids

GET /admin/user/group/treeList   
會列出目前系統內所有使用者群組，填入對應的使用者群組id到 group_ids

**Comment by ppuff1988** [comment]
應該有問題的是你進入編輯會員時，要怎麼把

列出所有群組的清單(checkbox list)
還有將user有的groups 綁定回去
